samples:
    sample1:
        sff: data/sff/her_b34.sff
    sample2:
        sff: data/sff/her_b64.sff
#    sample3:
#        sff: data/sff/her_f05.sff
#    sample4:
#        sff: data/sff/her_f49.sff
#    sample5:
#        sff: data/sff/her_p45.sff
#    sample6:
#        sff: data/sff/her_p78.sff
#    sample7:
#        sff: data/sff/her_r31.sff
#    sample8:
#        sff: data/sff/her_r61.sff

adaptors:
    "data/adaptors/adaptors.fa"

univec_url:
    "ftp://ftp.ncbi.nlm.nih.gov/pub/UniVec/UniVec"



software_params:
    pyrobayes:
        # None
    trimmomatic:
        "HEADCROP:12 MINLEN:39"
        # Delete first 12 nt and remove reads that are now less than 39 nt
    seqclean:
        slice_size: 1000 #-n number of sequences taken at once in each search
        # slice (default 2000)
        min_length: 40 #-l during cleaning, consider invalid the sequences
        # shorter than <minlen> (default 100)
        min_percent: 96 #-x minimum percent identity for an alignemnt with a
        # contaminant (default 96)
        min_length_vector: 11 #-y minimum length of a terminal vector hit to be
        # considered (>11, default 11)
    gsAssembler:
        minimum_sequence_length: 40 # -minlen 20. Flag to set the minimum read
        # length used in assembly and mapping computations. Reads of this
        # length will generally be classified as short tag reads, which are
        # treated separately from longer reads in computations (see Sections
        # 1.16.1.10 and 2.18.1.10).
        minimum_overlap_identity: 90 # -mi 90. A value of 100 matches only
        # identical sequences. Values below 50 may result in unpredictable
        # behavior, with very low values (i.e. 1) essentially matching all
        # reads.
        minimum_overlap_length: 50 # -ml 40 or -ml 90%. Flag to set the minimum
        # overlap length parameter, as either a minimum length in bases or a
        # percentage of read length.
        additional_params: "-force -m -tr -noace" # put here other flags
        # -force: overwrite output
        # -m: store reads in memory for fastest results
        # -tr: output trimmed reads
        # -noace: disable ace output
