samples_sff:
    sample1:
        sff: data/reads/222_FZUWXHW09.sff
    sample2:
        sff: data/reads/221_FZUWXHW01.sff

samples_fastq:
    sample3:
        fastq: data/reads/ERR047535.fastq.gz
    sample4:
        fastq: data/reads/ERR047541.fastq.gz

adaptors:
    "data/adaptors/adaptors.fa"

univec_url:
    "ftp://ftp.ncbi.nlm.nih.gov/pub/UniVec/UniVec"

software_params:
    pyrobayes:
        # None
    snowhite:
        minimum_sequence_length: 50
        # -m: <integer> minimum sequence length for cleaned reads
        # (default = 50bp, APPLIES TO -Q,-E,-L,-Y STEPS, NOT to -B,-D,-R)
        delete_temporary_files: T
        # -g: <T/F> delete all temporary (garbage) files (default = F)
        output_fastq: T
        # -R: <T/F> convert final output to fastq format (default = F, i.e. fasta format)
        split_in_subfiles: no
        # -B: <integer/FILENAME> split file into set number of subfiles, or according to barcodes in FILENAME (default = no splitting)
        barcodes_in_end: 5
        # -j: <5/3> look for barcodes at 5' or 3' ends (default = 5)
        number_of_mismatches: 2
        # -z: <integer> number of mismatches allowed when matching barcode (default = 0)
        minimum_quality: 35
        # -Q: <integer> minimum phred score under which to trim 3' ends (default = no trimming; suggest = 10)
        end_clipping: B
        # -E: <5/3/B/FILENAME> clip at 5', 3', Both, or according to sequences in FILENAME (default = 5)
        bases_to_clip: 0
        # -c: <integer> number of bases to clip off of all sequences (unless -E is FILENAME; default = 0)
        execute_tagdust: T
        # -D: <T/F> execute TagDust, assuming primer/adapter (-v) file is provided (default = F)
        false_discovery_rate: 0.01
        # -d: <decimal> false discovery rate (default = 0.01)
        execute_seqclean: T
        # -L: <T/F> execute SeqClean (default = F)
        execute_poly_trimming: T
        # -Y: <T/F> execute poly trimming as defined by all following parameters (default = F)
        poly_tail_min_repeat_length: 6
        # -l: <integer> minimum length of terminal A/T repeat (default = 6)
        poly_a_ends: B
        # -a: <3/5/B> poly A at 3', 5', or Both ends (default = 3)
        poly_t_ends: B
        # -t: <3/5/B> poly T at 3', 5', or Both ends (default = 5)
        poly_tail_terminal_bases_cap: 10
        # -b: <integer> number of terminal bases to look beyond for start of terminal poly A/T (default = 0)
        poly_tail_minimum_repeat_length: 2
        # -r: <integer> minimum length of A/T repeat inside of -b to consider as poly A/T (min = 2, default = 10)
        internal_poly_minimum_length: 15
        #-i: <integer> minimum length of internal poly A/T sequence to consider as poly A/T (default = 100bp, extreme case)
        keep_longer_end: F
        # -k: <T/F> keep the longer end of sequence broken by a single internal polyA/T (default = F)
        ns_as_a_or_t: T
        # -n: <T/F> interpret Ns within A/T repeats as As or Ts (default = T)
        allow_wobble: T
        # -w: <T/F> allow wobble: i.e. ignore single alternative bases within A/T repeats (default = T)
    trimmomatic:
        params:
            "LEADING:20 TRAILING:20 AVGQUAL:30 MINLEN:50 TOPHRED33"
    gsAssembler:
        minimum_sequence_length: 45 # -minlen 20. Flag to set the minimum read
        # length used in assembly and mapping computations. Reads of this
        # length will generally be classified as short tag reads, which are
        # treated separately from longer reads in computations (see Sections
        # 1.16.1.10 and 2.18.1.10).
        minimum_overlap_identity: 95 # -mi 90. A value of 100 matches only
        # identical sequences. Values below 50 may result in unpredictable
        # behavior, with very low values (i.e. 1) essentially matching all
        # reads.
        minimum_overlap_length: 50 # -ml 40 or -ml 90%. Flag to set the minimum
        # overlap length parameter, as either a minimum length in bases or a
        # percentage of read length.
        additional_params: "-force -m -tr -noace -siom 48" # put here other flags
        # -force: overwrite output
        # -m: store reads in memory for fastest results
        # -tr: output trimmed reads
        # -noace: disable ace output
        # -siom 30: serial i/o in memory. Max RAM to use: 30 Gb 
    multiqc:
        template: default # simple default_dev geo default
        data_format: tsv # tsv yaml json
        additional_params: ""
